### ISSUE TITLE
Improvement in websites

### ISSUE THREAD

**Issue by Hemanth3401** [ThejasreeKilari/Web_development_journey#4]
I Would propose like making one website which would be a collection of all the days and which can be seen to everyone. Would also be helpful in learning more and they can see in live at one page and use GitHub pages to host them.   I wanted to ask where did you find to do all this resource. I mean did you make a plan or doing rough plans of day to day?

**Comment by ThejasreeKilari** [comment]
Yes @Hemanth987. I'll look into it. Thank you so much!
I'm learning from freecodecamp (Responsive Web Design) and an Youtube channel named "Online Tutorials".
